const assert=require('node:assert/strict');
const E=require('../src/engine.js');
let tests=0;
function test(name,fn){fn();tests++;console.log('PASS '+name);}
const die=(s,n)=>E.dispatch(s,{type:'die',value:n});
const release=s=>E.dispatch(s,{type:'release'});
const signal=(s,v)=>E.dispatch(s,{type:'signal',value:v});
const vote=(s,v)=>E.dispatch(s,{type:'vendor',votes:v});
function standard(s){const p=s.pending;if(p.sides)return die(s,p.kind==='solution'?2:p.kind==='event'?2:6);if(p.kind==='signal')return signal(s,'Red');if(p.kind==='vendor')return vote(s,[true,true,true]);return E.dispatch(s,{type:p.kind==='release'?'release':'next'});}
function until(s,predicate){for(let n=0;n<2000;n++){if(predicate(s))return s;assert.equal(s.status,'playing','Game ended before requested point');s=standard(s);}throw Error('Did not reach requested point');}
function round(s,n){return until(s,x=>x.round===n&&x.pending?.kind==='production'&&x.pending.team===0);}
test('Perfect factory: 30 Titans, material balance, no cash loss, tied winners',()=>{let s=E.newGame({target:30});s=until(s,x=>x.status==='ended');assert.equal(s.shipped,30);assert.deepEqual(s.buffers,[0,0,0,0,0]);assert.equal(s.result.type,'success');assert.equal(s.result.winners.length,6);assert(s.teams.every(t=>t.gold===10));});
test('Unknown and inapplicable event dice require rerolls without fees',()=>{let s=die(E.newGame(),1);for(const n of [1,4,3]){s=die(s,n);assert.equal(s.pending.kind,'event');assert.equal(s.tickets.length,0);}s=die(s,6);assert.equal(s.pending.kind,'signal');});
test('Inapplicable solution preserves signal; free fix does not restore lost unit',()=>{let s=signal(die(die(E.newGame(),1),2),'Red');s=die(s,4);assert.equal(s.pending.kind,'solution');s=die(s,3);s=die(s,6);s=release(s);assert.equal(s.buffers[0],1);assert.equal(s.teams[0].gold,10);});
test('Immediate 4h repair reduces partial capacity to zero, costs only 1',()=>{let s=die(signal(die(die(E.newGame(),1),2),'Red'),1);assert.equal(s.rows[0].hours,4);assert.equal(s.teams[0].gold,9);s=release(die(s,6));assert.equal(s.buffers[0],0);assert.equal(s.pending.team,2);s=die(s,6);assert.equal(s.rows[3].signal,'Idle');});
test('Future action is charged once and uses next-round nominal base 2',()=>{let s=die(signal(die(die(E.newGame(),1),6),'YF'),1);assert.equal(s.rows[0].hours,0);assert.equal(E.remaining(s,0),4);s=until(s,x=>x.round===2);assert.equal(s.rows.find(r=>r.round===2&&r.team===0).hours,4);assert.equal(s.pending.team,1);assert.equal(s.teams[0].gold,9);s=release(die(s,6));assert.equal(s.rows.find(r=>r.round===2&&r.team===0).output,1);});
test('Analysis occurs before production and 8h repair suppresses dice',()=>{let s=signal(die(die(E.newGame(),1),2),'YA');s=until(s,x=>x.pending?.kind==='analysis');assert.equal(s.round,2);s=die(s,6);assert.equal(s.rows.find(r=>r.round===2&&r.team===0).hours,8);assert.equal(s.pending.team,1);assert.equal(s.teams[0].gold,8);});
test('Mandatory red on breakdown; only root cause is valid',()=>{let s=die(die(E.newGame(),1),10);assert.equal(s.pending.kind,'solution');assert.throws(()=>signal(s,'YA'));s=die(s,3);assert.equal(s.pending.kind,'solution');s=die(s,2);assert.equal(s.teams[0].gold,8);assert.equal(s.rows[0].hours,8);});
test('Voluntary vendor change: atomic charges, no current reversal, protection rerolls',()=>{let s=vote(die(die(E.newGame(),1),8),[true,false,true]);assert.deepEqual(s.teams.slice(0,3).map(t=>t.gold),[8,8,8]);assert.equal(s.vendor.protectedThrough,6);assert.equal(s.vendor.count,0);assert.equal(s.rows[0].hours,0);s=die(s,1);s=die(s,8);assert.equal(s.pending.kind,'event');s=die(s,2);s=die(signal(s,'Red'),3);s=release(s);assert.deepEqual(s.buffers.slice(0,2),[1,1]);});
test('Third raw-material occurrence forces exactly 32h and 7 gold for each shop',()=>{let s=E.newGame();s=vote(die(die(s,1),8),[false,false,false]);s=vote(die(die(s,1),8),[false,false,false]);s=release(s);s=die(die(s,1),8);assert.deepEqual(s.teams.slice(0,3).map(t=>t.gold),[3,3,3]);assert(s.teams.slice(0,3).every((t,i)=>E.remaining(s,i)===32));assert.equal(s.tickets.length,3);s=until(s,x=>x.round===2);assert.equal(s.pending.kind,'release');assert(s.teams.slice(0,3).every((t,i)=>E.remaining(s,i)===24));s=until(s,x=>x.round===5);assert(s.teams.slice(0,3).every((t,i)=>E.remaining(s,i)===0));assert.deepEqual(s.teams.slice(0,3).map(t=>t.gold),[3,3,3]);});
test('Vendor protection has exact r+5/r+6 boundary and team applicability',()=>{const s=E.newGame();s.vendor.protectedThrough=9;s.round=9;assert.equal(E.validEvent(s,0,8),false);s.round=10;assert.equal(E.validEvent(s,0,8),true);assert.equal(E.validEvent(s,3,8),false);assert.equal(E.validEvent(s,0,4),false);assert.equal(E.validEvent(s,3,4),true);});
test('Subassembly rework charges upstream origin, retains input and holds output',()=>{let s=until(E.newGame(),x=>x.pending?.kind==='production'&&x.pending.team===3);s=die(die(die(s,1),4),4);assert.equal(s.pending.kind,'origin');s=die(s,1);assert.equal(s.teams[0].gold,8);assert.equal(s.teams[3].gold,10);assert.equal(E.remaining(s,0),8);s=release(s);assert.deepEqual(s.buffers,[2,2,2,0,0]);assert.equal(s.rows[3].output,0);assert.equal(s.rows[4].signal,'Idle');});
test('Final assembly and Quality rework use correct immediate suppliers',()=>{for(const [team,originDie,origin] of [[4,1,3],[4,6,2],[5,null,4]]){let s=until(E.newGame(),x=>x.pending?.kind==='production'&&x.pending.team===team);s=die(die(die(s,1),4),4);if(originDie)s=die(s,originDie);assert.equal(s.teams[origin].gold,8);assert.equal(s.teams[team].gold,10);assert.equal(s.rows[team].hold,true);}});
test('Overlapping repair tickets queue sequentially and are not charged twice',()=>{let s=die(signal(die(die(E.newGame(),1),2),'YF'),2);s=until(s,x=>x.pending?.kind==='production'&&x.pending.team===3);s=die(die(die(die(s,1),4),4),1);assert.equal(E.remaining(s,0),16);assert.equal(s.teams[0].gold,6);s=until(s,x=>x.round===2);assert.equal(E.remaining(s,0),8);assert.equal(s.rows.find(r=>r.round===2&&r.team===0).hours,8);s=until(s,x=>x.round===3);assert.equal(E.remaining(s,0),0);assert.equal(s.teams[0].gold,6);assert.equal(s.rows.find(r=>r.round===3&&r.team===0).hours,8);});
test('Round-15 deferred analysis is charged in settlement without shipments',()=>{let s=round(E.newGame(),15);s=signal(die(die(s,1),2),'YA');s=until(s,x=>x.settlement);assert.equal(s.pending.kind,'analysis');const shipped=s.shipped;s=die(s,6);assert.equal(s.status,'ended');assert.equal(s.result.type,'practice');assert.equal(s.teams[0].gold,8);assert.equal(s.shipped,shipped);assert.equal(E.remaining(s,0),8);assert(s.tickets.at(-1).settlement);});
test('Final settlement can cause bankruptcy despite completing production',()=>{let s=E.newGame({target:1});for(const n of [1,3,5,7]){s=round(s,n);s=die(die(die(s,1),10),2);}s=round(s,15);assert.equal(s.teams[0].gold,2);s=signal(die(die(s,1),2),'YA');s=until(s,x=>x.settlement);s=die(s,6);assert.equal(s.result.type,'bankrupt');assert.equal(s.teams[0].gold,0);assert(s.shipped>=1);});
test('Bankruptcy at zero halts before unreleased output',()=>{let s=E.newGame();for(const n of [1,3,5,7,9]){s=round(s,n);s=die(die(die(s,1),10),2);}assert.equal(s.status,'ended');assert.equal(s.teams[0].gold,0);assert.equal(s.result.type,'bankrupt');assert.deepEqual(s.result.winners,[]);assert.equal(s.rows.find(r=>r.round===9&&r.team===0).released,false);assert.throws(()=>E.dispatch(s,{type:'next'}));});
test('A surviving factory can miss its target',()=>{let s=die(signal(die(die(E.newGame({target:30}),1),2),'Red'),3);s=until(s,x=>x.status==='ended');assert.equal(s.result.type,'targetMissed');assert.equal(s.shipped,29);});
test('Save/load, strict replay, undo and CSV',()=>{let s=vote(die(die(E.newGame({name:'Session',target:12}),1),8),[true,true,false]);assert.deepEqual(E.deserialize(E.serialize(s)),s);const back=E.undo(s);assert.equal(back.pending.kind,'vendor');assert.equal(back.teams[0].gold,10);assert.throws(()=>E.deserialize('{bad'));assert.throws(()=>E.deserialize(JSON.stringify({format:'ironhold-save',version:E.VERSION,config:{},actions:[{type:'release'}]})));assert.throws(()=>die(s,0));assert.throws(()=>die(s,1.5));assert.throws(()=>E.newGame({target:0}));const csv=E.csv(s);assert(csv.includes('closing_gold'));assert(csv.includes('"no"'));assert.deepEqual(E.deserialize(E.serialize(back)),back);});
test('Randomized legal games reconcile cash, inventory and round limits',()=>{let seed=90421;const rng=n=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed%n;};for(let g=0;g<25;g++){let s=E.newGame({target:g%2?12:null});for(let n=0;s.status==='playing';n++){assert(n<2000);const p=s.pending;if(p.sides)s=die(s,rng(p.sides)+1);else if(p.kind==='signal')s=signal(s,['Red','YA','YF'][rng(3)]);else if(p.kind==='vendor')s=vote(s,[!!rng(2),!!rng(2),!!rng(2)]);else s=E.dispatch(s,{type:p.kind==='release'?'release':'next'});E.assertState(s);}assert.deepEqual(E.deserialize(E.serialize(s)),s);}});
console.log(`\n${tests} tests passed.`);
