const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const d=new JSDOM(fs.readFileSync(__dirname+'/../index.html','utf8'),{url:'https://example.test/',runScripts:'dangerously',beforeParse(w){w.confirm=()=>true;}});const w=d.window,$=id=>w.document.getElementById(id),role=x=>w.document.querySelector(`[data-role="${x}"]`).click(),submit=id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert(!$('role-entry').hidden);assert($('master-workspace').hidden);role(0);assert($('role-entry-message').textContent.includes('must start'));role('gm');submit('setup-form');assert(!$('master-workspace').hidden);
$('transfer-reason').value='Treasury test';$('transfer-amount').value=3;submit('transfer-form');
$('switch-role').click();role(0);assert(!$('guild-workspace').hidden);assert($('master-workspace').hidden);assert($('guild-workspace').textContent.includes('Your gold'));assert(!$('guild-workspace').querySelector('#gm-form'));assert(!$('guild-workspace').textContent.includes('13 gold'));
assert(!$('guild-panel-dice').hidden);assert($('guild-panel-overview').hidden);$('guild-tab-overview').click();assert($('guild-panel-dice').hidden);assert(!$('guild-panel-overview').hidden);$('guild-tab-overview').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));assert(!$('guild-panel-dice').hidden);assert.equal($('guild-tab-dice').getAttribute('aria-selected'),'true');
$('guild-die').value=2;$('guild-record').click();assert($('guild-workspace').textContent.includes('D10 required'));assert(!$('guild-roll'));$('guild-continue').click();assert($('guild-roll').textContent.includes('D10'));$('guild-die').value=2;$('guild-record').click();$('guild-continue').click();w.document.querySelector('[data-guild-signal=YA]').click();assert(!$('guild-roll'));assert($('guild-workspace').textContent.includes('Waiting'));
$('guild-amount').value=1;$('guild-reason').value='Own guild help';submit('guild-transfer-form');
const snap=w.localStorage.getItem('ironhold-standalone-3.0.0');$('switch-role').click();role('gm');assert(!$('master-workspace').hidden);$('open-reveal').click();assert(!$('showcase-workspace').hidden);assert($('master-workspace').hidden);assert($('reveal-content').textContent.includes('Treasury test'));assert.equal(w.localStorage.getItem('ironhold-standalone-3.0.0'),snap);$('close-reveal').click();assert(!$('master-workspace').hidden);
// Incoming transfer appears in receiving guild's movements; no other guild's balances.
$('switch-role').click();role(1);assert($('guild-workspace').textContent.includes('Treasury test'));assert($('guild-workspace').textContent.includes('from Shop 1'));assert.equal($('guild-workspace').querySelectorAll('.guild-private-header img').length,1);
d.window.close();console.log('PASS role entry, setup gating, own-guild turns, separate D10, restricted controls, transfers, incoming history and read-only GM reveal.');
