(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Ironhold=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='3.0.0';
const TEAMS=[
 {name:'Emberborn Smiths',role:'Shop 1',inputs:[],out:0},
 {name:"Gearwright’s Consortium",role:'Shop 2',inputs:[],out:1},
 {name:'Arcane Weavers',role:'Shop 3',inputs:[],out:2},
 {name:'Hammer and Anvil Guild',role:'Subassembly',inputs:[0,1],out:3},
 {name:'Titanwrights',role:'Final assembly',inputs:[3,2],out:4},
 {name:'Order of the Unerring Gaze',role:'Quality inspection',inputs:[4],out:5}
];
const STAGES=[[0,1],[2,3],[4],[5]];
const BUFFERS=['Component 1','Component 2','Component 3','Subassemblies','Uninspected Titans'];
const EVENTS={2:'Machine failure',4:'Defective part',6:'Machine misalignment',8:'Defective raw material',10:'Machine breakdown'};
const SOLUTIONS={1:'Stop and investigate',2:'Root cause analysis',3:'Software / parts fix',4:'Rework'};
const clone=x=>JSON.parse(JSON.stringify(x));
function check(b,m){if(!b)throw new Error(m);}
function configuration(c={}){check(c&&typeof c==='object'&&!Array.isArray(c),'Invalid setup.');const target=c.target==null?null:c.target;check(target===null||(Number.isInteger(target)&&target>=1&&target<=30),'Target must be a whole number from 1 to 30.');const name=c.name==null?'Classroom session':c.name;check(typeof name==='string'&&name.length<=80,'Session name must be at most 80 characters.');const startingGold=c.startingGold??10;check(Number.isInteger(startingGold)&&startingGold>=1&&startingGold<=1000,'Starting gold must be a whole number from 1 to 1000.');return {target,name,startingGold};}
function log(s,text,team=null,type='info',data={}){s.log.push({id:s.log.length+1,round:s.round,settlement:s.settlement,team,type,text,...data});}
function newGame(config={}){const s={version:VERSION,config:configuration(config),round:1,stage:0,cursor:0,status:'playing',settlement:false,teams:TEAMS.map(()=>({gold:configuration(config).startingGold,units:0,queue:[]})),buffers:[0,0,0,0,0],shipped:0,vendor:{count:0,protectedThrough:0,changes:0},analyses:[],tickets:[],cashMoves:[],exceptions:[],rows:[],rounds:[],log:[],actions:[],pending:null,result:null};log(s,`The six guilds begin with ${s.config.startingGold} gold each.`);startRound(s);return s;}
function row(s,t){return s.rows.find(r=>r.round===s.round&&r.team===t);}
function remaining(s,t){return s.teams[t].queue.reduce((n,q)=>n+q.hours,0);}
function setPending(s,kind,team=null,sides=null){s.pending={kind,team,sides};}
function bankrupt(s){if(s.teams.some(t=>t.gold<=0)){s.status='ended';s.pending=null;s.result={type:'bankrupt',winners:[]};log(s,'Factory stopped: at least one guild has zero or negative gold. No Master Guild is awarded.',null,'end');return true;}return false;}
function ticket(s,team,hours,due,reason){check([0,4,8,32].includes(hours),'Invalid repair ticket.');const cost=({0:0,4:1,8:2,32:7})[hours];const id=s.tickets.length+1;s.tickets.push({id,round:s.round,settlement:s.settlement,team,hours,cost,due,reason});s.teams[team].gold-=cost;if(hours)s.teams[team].queue.push({id,hours,due});log(s,`${TEAMS[team].role}: ${reason}. ${hours} repair hours, ${cost} gold charged${hours?`; due round ${due}`:''}.`,team,'ticket',{hours,cost,due,ticketId:id});}
function serve(s,t){const r=row(s,t);let available=8-r.hours;for(const q of s.teams[t].queue){if(q.due<=s.round&&available>0){const used=Math.min(q.hours,available);q.hours-=used;available-=used;r.hours+=used;}}s.teams[t].queue=s.teams[t].queue.filter(q=>q.hours>0);}
function startRound(s){s.stage=0;s.cursor=0;s.settlement=false;TEAMS.forEach((_,t)=>s.rows.push({round:s.round,team:t,base:null,event:null,signal:'',solution:null,hours:0,output:0,released:false,done:false,hold:false,productionDie:null,eventDice:[],solutionDice:[]}));log(s,`Round ${s.round} begins.`,null,'round');startAnalyses(s);}
function startAnalyses(s){const due=s.analyses.find(a=>a.due<=(s.settlement?16:s.round));if(due){setPending(s,'analysis',due.team,6);s.pending.analysisId=due.id;return;}if(bankrupt(s))return;if(s.settlement){finishGame(s);return;}TEAMS.forEach((_,t)=>serve(s,t));prepareTeam(s);}
function inputsAvailable(s,t){return TEAMS[t].inputs.length?Math.min(...TEAMS[t].inputs.map(b=>s.buffers[b])):Infinity;}
function prepareTeam(s){if(s.status!=='playing')return;if(s.cursor>=STAGES[s.stage].length){setPending(s,'release');return;}const t=STAGES[s.stage][s.cursor],r=row(s,t);if(r.hours>0){r.base=2;r.signal='Maintenance';r.done=true;log(s,`${TEAMS[t].role}: ${r.hours} repair hours served; no production die.`,t);s.cursor++;prepareTeam(s);return;}if(inputsAvailable(s,t)===0){r.base=2;r.signal='Idle';r.done=true;log(s,`${TEAMS[t].role}: waiting for a complete input set; no dice or fine.`,t);s.cursor++;prepareTeam(s);return;}setPending(s,'production',t,6);}
function doneTeam(s){const t=STAGES[s.stage][s.cursor];row(s,t).done=true;if(bankrupt(s))return;s.cursor++;prepareTeam(s);}
function validEvent(s,t,n){return n%2===0&&n>=2&&n<=10&&!(n===4&&t<3)&&!(n===8&&(t>=3||s.round<=s.vendor.protectedThrough));}
function validSolution(event,n){return event===2||event===6?[1,2,3].includes(n):event===4?[2,4].includes(n):event===10?n===2:false;}
function vendorChange(s,forced){const hours=forced?32:8;for(let t=0;t<3;t++)ticket(s,t,hours,s.round+1,forced?'Forced vendor change':'Voluntary vendor change');s.vendor.count=0;s.vendor.protectedThrough=s.round+5;s.vendor.changes++;log(s,`Vendor changed. Protection covers the rest of this round through round ${s.vendor.protectedThrough}.`,null,'vendor');doneTeam(s);}
function rework(s,origin){const t=s.pending.team,r=row(s,t);r.hold=true;ticket(s,origin,8,s.round+1,`Rework detected at ${TEAMS[t].role}`);log(s,`${TEAMS[t].role}: output held at zero; inputs retained. Repair assigned to ${TEAMS[origin].role}.`,t,'rework');doneTeam(s);}
function applyDie(s,n){const p=s.pending,t=p.team;check(Number.isInteger(n)&&n>=1&&n<=p.sides,`Enter a whole number from 1 to ${p.sides}.`);log(s,`${p.kind}: d${p.sides} = ${n}.`,t,'die',{kind:p.kind,sides:p.sides,value:n});
 if(p.kind==='analysis'){const a=s.analyses.find(a=>a.id===p.analysisId);check(a,'Analysis task missing.');const hours=n<=2?0:n<=4?4:8;ticket(s,t,hours,s.settlement?16:s.round,'Deferred analysis');s.analyses=s.analyses.filter(a=>a.id!==p.analysisId);startAnalyses(s);return;}
 const r=row(s,t);
 if(p.kind==='production'){r.productionDie=n;r.base=n<=3?1:2;if(r.base===2){r.signal='Green';doneTeam(s);}else setPending(s,'event',t,10);return;}
 if(p.kind==='event'){r.eventDice.push(n);if(!validEvent(s,t,n)){log(s,n%2?'Unknown cause: roll again until an applicable even cause is found.':'This cause does not apply here. Reroll without a charge.',t,'reroll');return;}r.event=n;log(s,`${TEAMS[t].role}: ${EVENTS[n]}.`,t,'incident');if(n===8){r.signal='Vendor';s.vendor.count++;log(s,`Current vendor occurrence ${s.vendor.count} of 3.`,t);if(s.vendor.count===3)vendorChange(s,true);else setPending(s,'vendor',t);return;}if(n===4||n===10){r.signal='Red';setPending(s,'solution',t,4);}else setPending(s,'signal',t);return;}
 if(p.kind==='solution'){r.solutionDice.push(n);if(!validSolution(r.event,n)){log(s,'This solution does not apply. Reroll; the selected signal is unchanged.',t,'reroll');return;}r.solution=n;if(n===4){if(t===5)rework(s,4);else setPending(s,'origin',t,6);return;}const hours=({1:4,2:8,3:0})[n];ticket(s,t,hours,r.signal==='YF'?s.round+1:s.round,SOLUTIONS[n]);if(!bankrupt(s)){if(r.signal==='Red')serve(s,t);doneTeam(s);}return;}
 if(p.kind==='origin'){rework(s,t===3?(n<=3?0:1):(n<=3?3:2));return;}
 throw new Error('No die is expected now.');
}
function release(s){const batch=STAGES[s.stage];for(const t of batch){const r=row(s,t);check(r.done,'Finish all decisions before releasing output.');const cap=r.hold?0:Math.max(0,r.base-r.hours/4);const output=Math.min(cap,inputsAvailable(s,t));r.output=output;r.released=true;for(const input of TEAMS[t].inputs)s.buffers[input]-=output;if(t===5)s.shipped+=output;else s.buffers[TEAMS[t].out]+=output;s.teams[t].units+=output;log(s,`${TEAMS[t].role}: ${output} good unit${output===1?'':'s'} ${t===5?'approved and shipped':'transferred'}.`,t,'output',{output});}if(s.stage===3){s.rounds.push({round:s.round,shipped:s.rows.find(r=>r.team===5&&r.round===s.round).output,cumulative:s.shipped,gold:s.teams.map(t=>t.gold),buffers:clone(s.buffers)});setPending(s,'roundEnd');log(s,`Round ${s.round} complete. Total approved Titans: ${s.shipped}.`);}else{s.stage++;s.cursor=0;prepareTeam(s);}}
function finishGame(s){s.status='ended';s.pending=null;const success=s.config.target!==null&&s.shipped>=s.config.target;const best=Math.max(...s.teams.map(t=>t.gold));s.result={type:s.config.target===null?'practice':success?'success':'targetMissed',winners:success?s.teams.map((t,i)=>t.gold===best?i:null).filter(i=>i!==null):[]};log(s,success?'Ironhold defended: target met and all guilds survived.':s.config.target===null?'Practice complete. Review shipments, gold and remaining repairs.':'The factory survived, but the shipment target was missed.',null,'end');}
function assertState(s){check(s.buffers.every(x=>Number.isInteger(x)&&x>=0),'Inventory invariant failed.');check(s.shipped>=0&&s.shipped<=30,'Shipment invariant failed.');for(let t=0;t<6;t++){check(s.teams[t].gold===s.config.startingGold+s.cashMoves.filter(x=>x.team===t).reduce((a,x)=>a+x.delta,0)-s.tickets.filter(x=>x.team===t).reduce((a,x)=>a+x.cost,0),'Gold reconciliation failed.');check(s.teams[t].queue.every(q=>q.hours>0&&q.hours%4===0),'Repair queue invariant failed.');}check(s.rows.every(r=>r.hours>=0&&r.hours<=8&&r.hours%4===0&&r.output>=0&&r.output<=2),'Round invariant failed.');const u=s.teams.map(t=>t.units);check(s.buffers[0]===u[0]-u[3]&&s.buffers[1]===u[1]-u[3]&&s.buffers[2]===u[2]-u[4]&&s.buffers[3]===u[3]-u[4]&&s.buffers[4]===u[4]-u[5]&&s.shipped===u[5],'Material balance failed.');return true;}
function teamIndex(t){check(Number.isInteger(t)&&t>=0&&t<6,'Choose a guild.');}
function reasonText(text){check(typeof text==='string'&&text.trim().length>=3&&text.trim().length<=240,'Enter a reason of 3–240 characters.');return text.trim();}
function cashMove(s,team,delta,kind,reason,other=null,instructor=''){s.teams[team].gold+=delta;s.cashMoves.push({round:s.round,settlement:s.settlement,team,delta,kind,reason,other,instructor});}
function refreshRoundGold(s){const last=s.rounds.at(-1);if(!s.settlement&&last?.round===s.round)last.gold=s.teams.map(t=>t.gold);}
function dispatch(state,action){check(state.status==='playing','This game has ended.');check(action&&typeof action==='object','Invalid action.');const s=clone(state),p=s.pending;let a;
 if(action.type==='transfer'){
 const {from,to,amount}=action;teamIndex(from);teamIndex(to);check(from!==to,'Choose two different guilds.');check(Number.isInteger(amount)&&amount>0&&amount<=1000,'Transfer a whole number from 1 to 1000 gold.');check(s.teams[from].gold-amount>=1,'The sending guild must retain at least 1 gold.');const reason=reasonText(action.reason);
 cashMove(s,from,-amount,'transfer',reason,to);cashMove(s,to,amount,'transfer',reason,from);a={type:'transfer',from,to,amount,reason};log(s,`${TEAMS[from].role} transfers ${amount} gold to ${TEAMS[to].role}: ${reason}`,from,'transfer');refreshRoundGold(s);
 }
 else if(action.type==='exception'){
 const kind=action.kind,reason=reasonText(action.reason),instructor=reasonText(action.instructor);check(['gold','downtime','note'].includes(kind),'Choose a supported exception.');const team=action.team;check(team===null||(Number.isInteger(team)&&team>=0&&team<6),'Choose a guild or all guilds.');const selected=team===null?[0,1,2,3,4,5]:[team];let amount=0;
 if(kind==='gold'){amount=action.amount;check(Number.isInteger(amount)&&amount!==0&&Math.abs(amount)<=1000,'Gold adjustment must be a nonzero whole number between -1000 and 1000.');for(const t of selected)cashMove(s,t,amount,'game-master',reason,null,instructor);}
 if(kind==='downtime'){check(!s.settlement&&s.round<15,'Next-round downtime is available only in rounds 1–14.');amount=action.amount;check([4,8,16,32].includes(amount),'Choose 4, 8, 16 or 32 downtime hours.');for(const t of selected){const id=s.tickets.length+1;s.tickets.push({id,round:s.round,settlement:false,team:t,hours:amount,cost:0,due:s.round+1,reason:'Game Master downtime: '+reason});s.teams[t].queue.push({id,hours:amount,due:s.round+1});}}
 a={type:'exception',kind,team,amount,reason,instructor};s.exceptions.push({...a,round:s.round,settlement:s.settlement});log(s,`Game Master ${instructor} · ${team===null?'all guilds':TEAMS[team].role} · ${kind}${kind==='gold'?': '+(amount>0?'+':'')+amount+' gold':kind==='downtime'?': '+amount+'h next round, no gold charge':''} · ${reason}`,team,'exception');refreshRoundGold(s);if(kind==='gold')bankrupt(s);
 }
 else if(action.type==='die'){check(['production','event','solution','origin','analysis'].includes(p.kind),'A die is not expected.');a={type:'die',value:action.value};applyDie(s,a.value);}
 else if(action.type==='signal'){check(p.kind==='signal','A signal is not expected.');check(['YA','YF','Red'].includes(action.value),'Choose a permitted signal.');a={type:'signal',value:action.value};const r=row(s,p.team);r.signal=a.value;log(s,`${TEAMS[p.team].role} chooses ${a.value}.`,p.team,'signal');if(a.value==='YA'){s.analyses.push({id:s.actions.length+1,team:p.team,due:s.round+1});doneTeam(s);}else setPending(s,'solution',p.team,4);}
 else if(action.type==='vendor'){check(p.kind==='vendor','A vendor vote is not expected.');check(Array.isArray(action.votes)&&action.votes.length===3&&action.votes.every(v=>typeof v==='boolean'),'Record all three shop votes.');a={type:'vendor',votes:action.votes.slice()};const yes=a.votes.filter(Boolean).length;log(s,`Vendor vote: ${a.votes.map((v,i)=>`Shop ${i+1} ${v?'change':'keep'}`).join(', ')}.`,null,'vote');if(yes>=2)vendorChange(s,false);else{log(s,'Vendor retained; occurrence count carries forward.');doneTeam(s);}}
 else if(action.type==='release'){check(p.kind==='release','Output is not ready to release.');a={type:'release'};release(s);}
 else if(action.type==='next'){check(p.kind==='roundEnd','Complete the round first.');a={type:'next'};if(s.round===15){s.settlement=true;log(s,'Final settlement begins. No further production is permitted.');startAnalyses(s);}else{s.round++;startRound(s);}}
 else throw new Error('Unknown action.');
 s.actions.push(a);assertState(s);return s;
}
function replay(config,actions){check(Array.isArray(actions)&&actions.length<=10000,'Invalid or oversized game history.');let s=newGame(config);for(const a of actions)s=dispatch(s,a);return s;}
function serialize(s){return JSON.stringify({format:'ironhold-save',version:VERSION,config:s.config,actions:s.actions},null,2);}
function deserialize(text){check(typeof text==='string'&&text.length<=2000000,'Save file is too large.');let data;try{data=JSON.parse(text);}catch{throw new Error('This is not a valid JSON save file.');}check(data&&data.format==='ironhold-save'&&data.version===VERSION,'This file is not an Ironhold 3.0.0 save.');return replay(data.config,data.actions);}
function undo(s){check(s.actions.length>0,'There is no action to undo.');return replay(s.config,s.actions.slice(0,-1));}
function csv(s){const rows=[['round','team','guild','production_die','base_capacity','event','signal','solution','hours_served','good_units','released','new_cost_gold','closing_gold','phase','movement_kind','counterparty','gold_delta','reason','instructor']];for(const r of s.rows){const costs=s.tickets.filter(t=>t.team===r.team&&!t.settlement&&t.round===r.round).reduce((n,t)=>n+t.cost,0);const spent=s.tickets.filter(t=>t.team===r.team&&!t.settlement&&t.round<=r.round).reduce((n,t)=>n+t.cost,0);rows.push([r.round,TEAMS[r.team].role,TEAMS[r.team].name,r.productionDie??'',r.base??'',EVENTS[r.event]||'',r.signal,SOLUTIONS[r.solution]||'',r.hours,r.output,r.released?'yes':'no',costs,s.config.startingGold-spent+s.cashMoves.filter(x=>x.team===r.team&&!x.settlement&&x.round<=r.round).reduce((n,x)=>n+x.delta,0),'production']);}if(s.settlement)TEAMS.forEach((t,i)=>rows.push(['settle',t.role,t.name,'','','','','',0,0,'no',s.tickets.filter(x=>x.team===i&&x.settlement).reduce((n,x)=>n+x.cost,0),s.teams[i].gold,'settlement']));for(const m of s.cashMoves)rows.push([m.settlement?'settle':m.round,TEAMS[m.team].role,TEAMS[m.team].name,'','','','','','','','','','',m.settlement?'settlement':'cash movement',m.kind,m.other===null?'':TEAMS[m.other].role,m.delta,m.reason,m.instructor]);for(const e of s.exceptions)rows.push([e.settlement?'settle':e.round,e.team===null?'All guilds':TEAMS[e.team].role,'','','','','','','','','','','','exception',e.kind,'','',e.reason+(e.kind==='gold'?' ('+e.amount+' gold per selected guild)':e.kind==='downtime'?' ('+e.amount+'h next round)':''),e.instructor]);return rows.map(r=>r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\r\n');}
return {VERSION,TEAMS,STAGES,BUFFERS,EVENTS,SOLUTIONS,newGame,dispatch,replay,serialize,deserialize,undo,csv,remaining,validEvent,validSolution,assertState};
});
