(function(){
'use strict';
const E=window.Ironhold,$=id=>document.getElementById(id),KEY='ironhold-standalone-3.0.0';let state=null,tab='play',storageOK=true;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const role=t=>E.TEAMS[t].role;
function message(text,error=false){$('message').textContent=text;$('message').hidden=!text;$('message').classList.toggle('error',error);}
function switchTab(value){tab=value;for(const name of ['play','ledger','rules'])$(name+'-view').hidden=name!==value;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===value)));}
function persist(){if(!state)return;try{localStorage.setItem(KEY,E.serialize(state));storageOK=true;}catch{storageOK=false;}}
function update(){render();persist();if(state)$('autosave').textContent=storageOK?'Autosaved in this browser. Download a game save before leaving or changing devices.':'Browser storage is unavailable. Use Save game to keep your progress.';}
function act(action){try{state=E.dispatch(state,action);message('');update();}catch(err){message(err.message,true);}}
function dice(sides){const limit=Math.floor(4294967296/sides)*sides;let value;do{const a=new Uint32Array(1);crypto.getRandomValues(a);value=a[0];}while(value>=limit);return value%sides+1;}
function download(name,text,mime){const url=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function stageName(){return state.settlement?'Final settlement':`Round ${state.round} · Stage ${state.stage+1} of 4`;}
function badge(signal){const cls=signal==='Green'?'green':signal==='Red'||signal==='Maintenance'?'red':['YF','YA','Vendor'].includes(signal)?'yellow':'';return `<span class="badge ${cls}">${esc(signal||'Awaiting turn')}</span>`;}
function pendingHelp(p){const r=state.rows.find(r=>r.round===state.round&&r.team===p.team);if(p.kind==='production')return ['Production roll','1–3: one-unit base capacity. 4–6: two-unit base capacity. Inputs and repairs can reduce the actual transfer.'];if(p.kind==='event')return ['Find the cause','Roll d10. Odd or inapplicable outcomes require another roll. A physical 0 means 10.'];if(p.kind==='solution'){const valid=[1,2,3,4].filter(n=>E.validSolution(r.event,n));return ['Find an applicable solution',`${E.EVENTS[r.event]}. Valid faces: ${valid.join(', ')}. Other results reroll without changing the signal.`];}if(p.kind==='origin')return ['Identify the rework origin',p.team===3?'1–3: Shop 1. 4–6: Shop 2. The origin pays 2 gold and repairs next round.':'1–3: Subassembly. 4–6: Shop 3. The origin pays 2 gold and repairs next round.'];return ['Resolve deferred analysis','1–2: close at no cost. 3–4: 4h / 1 gold. 5–6: 8h / 2 gold. '+(state.settlement?'No more production occurs.':'Repair hours are served before this round’s production.')];}
function actionPanel(){const p=state.pending;$('phase-label').textContent=stageName();if(!p){$('action').innerHTML='<h2 id="action-title">The session is complete</h2><p>Review the factory result, compare guild decisions and export your ledger.</p><button id="review-ledger" class="primary">Review the ledger</button>';$('review-ledger').onclick=()=>switchTab('ledger');return;}
 let html=p.team!==null?`<p class="guild-name">${esc(role(p.team))} · ${esc(E.TEAMS[p.team].name)}</p>`:'';
 if(p.sides){const [heading,help]=pendingHelp(p);const last=[...state.log].reverse().find(x=>x.type==='die');html+=`<h2 id="action-title">${heading}</h2><div class="die-box"><div class="die-face" aria-label="${p.sides}-sided die">d${p.sides}</div><p>${esc(help)}</p></div><button id="roll" class="primary">Roll virtual d${p.sides}</button><div class="manual-row"><label>Physical die result<input id="manual-die" type="number" min="1" max="${p.sides}" step="1" inputmode="numeric" aria-label="Physical die result"></label><button id="record-die">Record roll</button></div><p class="muted small">${last?`Last roll: ${esc(last.kind)} d${last.sides} = <b>${last.value}</b>.`:'Every die outcome is recorded in the history.'}</p>`;
 }
 else if(p.kind==='signal'){const r=state.rows.find(r=>r.round===state.round&&r.team===p.team);html+=`<h2 id="action-title">How will you respond?</h2><p>Partial capacity: 1. Cause: <b>${esc(E.EVENTS[r.event])}</b>. Discuss the downstream effect before choosing.</p><button class="decision" data-signal="YF"><b>Yellow · future action</b><small>Choose a solution and pay now. Serve repair hours next round.</small></button><button class="decision" data-signal="YA"><b>Yellow · further analysis</b><small>Resolve a 0h, 4h or 8h outcome next round.</small></button><button class="decision red" data-signal="Red"><b>Red · act immediately</b><small>Choose a solution and serve repair hours before releasing output.</small></button>`;}
 else if(p.kind==='vendor'){html+=`<h2 id="action-title">Keep or change the vendor?</h2><p>Occurrence <b>${state.vendor.count} of 3</b>. A majority for change charges each shop 2 gold and schedules 8 repair hours next round.</p><div class="votes">${[0,1,2].map(t=>`<label>${role(t)} vote<select id="vote-${t}"><option value="">Choose a vote</option><option value="keep">Keep vendor</option><option value="change">Change vendor</option></select></label>`).join('')}</div><button id="submit-vote" class="primary">Record the three votes</button>`;}
 else if(p.kind==='release'){html+=`<h2 id="action-title">Release stage ${state.stage+1} output</h2><p>All decisions for ${E.STAGES[state.stage].map(role).join(' and ')} are complete. Predict the actual output before releasing it.</p><div class="scroll"><table><thead><tr><th>Team</th><th>Base</th><th>Repair hours</th><th>Rework hold</th></tr></thead><tbody>${E.STAGES[state.stage].map(t=>{const r=state.rows.find(r=>r.round===state.round&&r.team===t);return `<tr><td>${role(t)}</td><td>${r.base}</td><td>${r.hours}</td><td>${r.hold?'Yes':'No'}</td></tr>`;}).join('')}</tbody></table></div><button id="release" class="primary">Transfer good units</button>`;}
 else if(p.kind==='roundEnd'){const cycleBreak=[5,10,15].includes(state.round);html+=`<h2 id="action-title">${state.round===15?'Production complete':cycleBreak?'Pause for the cycle debrief':`Round ${state.round} complete`}</h2><p>${state.rounds.at(-1).shipped} Titans shipped this round. ${state.shipped} approved in total.</p>${cycleBreak?'<div class="debrief"><h3>Discuss before continuing</h3><ul><li>Which shortage or repair constrained the factory?</li><li>Did saving local gold help the common mission?</li><li>What will your team do differently?</li></ul></div>':''}<p class="muted">${state.round===15?'Final settlement resolves any deferred analysis before scoring. Already-paid outstanding repairs are not charged again.':'Cash, inventories, vendor protection and queued repairs carry forward.'}</p><button id="next" class="primary">${state.round===15?'Settle outstanding analysis':'Begin round '+(state.round+1)}</button>`;}
 $('action').innerHTML=html;
 if($('roll'))$('roll').onclick=()=>{try{act({type:'die',value:dice(p.sides)});}catch(err){message('Virtual dice are unavailable. Enter a physical die result.',true);}};
 if($('record-die')){$('record-die').onclick=()=>act({type:'die',value:Number($('manual-die').value)});$('manual-die').onkeydown=e=>{if(e.key==='Enter')$('record-die').click();};}
 document.querySelectorAll('[data-signal]').forEach(b=>b.onclick=()=>act({type:'signal',value:b.dataset.signal}));
 if($('submit-vote'))$('submit-vote').onclick=()=>{const v=[0,1,2].map(t=>$('vote-'+t).value);if(v.some(x=>!x)){message('Record each of the three shop votes.',true);return;}act({type:'vendor',votes:v.map(x=>x==='change')});};
 if($('release'))$('release').onclick=()=>act({type:'release'});
 if($('next'))$('next').onclick=()=>act({type:'next'});
}
function render(){const playing=!!state;$('setup').hidden=playing;$('welcome').hidden=playing;$('game').hidden=!playing;for(const id of ['save','csv'])$(id).disabled=!playing;$('undo').disabled=!playing||!state.actions.length;if(!playing)return;
 const gold=state.teams.reduce((n,t)=>n+t.gold,0),target=state.config.target,repair=state.teams.reduce((n,_,i)=>n+E.remaining(state,i),0);
 $('metrics').innerHTML=`<div class="metric"><span>${esc(state.config.name||'Classroom session')}</span><strong>${state.settlement?'Settlement':'Round '+state.round+' / 15'}</strong><small>Cycle ${Math.ceil(state.round/5)} · ${['Early Dawn','Fires of Noon','Twilight of Battle'][Math.ceil(state.round/5)-1]}</small></div><div class="metric"><span>Approved Titans</span><strong>${state.shipped}${target!==null?' / '+target:''}</strong><small>${target===null?'Practice · no target victory':'All guilds must also survive'}</small><div class="progress"><span style="width:${Math.min(100,100*state.shipped/(target||30))}%"></span></div></div><div class="metric"><span>Total remaining gold</span><strong>${gold} / 60</strong><small>Every individual guild must stay above 0</small></div><div class="metric"><span>Outstanding work</span><strong>${repair} hours</strong><small>${state.analyses.length} analysis task${state.analyses.length===1?'':'s'} pending</small></div>`;
 actionPanel();
 const node=(label,count,unit)=>`<div class="node"><b>${label}</b><strong>${count}</strong><small>${unit}</small></div>`;
 $('network').innerHTML=[`<div class="flow-nodes">${node('Shop 1',state.buffers[0],'C1 waiting')}${node('Shop 2',state.buffers[1],'C2 waiting')}</div>`,`<div class="flow-nodes">${node('Shop 3',state.buffers[2],'C3 waiting')}${node('Subassembly',state.buffers[3],'waiting')}</div>`,`<div class="flow-nodes">${node('Final assembly',state.buffers[4],'awaiting inspection')}</div>`,`<div class="flow-nodes">${node('Quality approved',state.shipped,'Titans shipped')}</div>`].map((content,i)=>`<div class="flow-stage ${state.status==='playing'&&!state.settlement&&state.stage===i?'current':''}"><span>Stage ${i+1}</span>${content}</div>`).join('');
 $('vendor-info').innerHTML=`<p><b>Vendor:</b> ${state.vendor.count} / 3 occurrences · ${state.vendor.changes} change${state.vendor.changes===1?'':'s'}.</p><p>${state.round<=state.vendor.protectedThrough?`Protected through round <b>${state.vendor.protectedThrough}</b>; event 8 is rerolled.`:'No active protection. A third occurrence forces a change.'}</p>`;
 $('team-cards').innerHTML=E.TEAMS.map((team,t)=>{const own=state.teams[t],r=state.rows.find(r=>r.round===state.round&&r.team===t),queue=own.queue.map(q=>`${q.hours}h due R${q.due}`).join('; ');return `<article class="team-card ${state.pending?.team===t?'active':''} ${own.gold<=0?'bankrupt':''}"><p class="role">${team.role}</p><h3>${esc(team.name)}</h3><div class="team-line"><span class="money">${own.gold} <small>gold</small></span>${badge(r.signal)}</div><p><b>${r.released?r.output:'—'}</b> transferred this round · <b>${own.units}</b> total units</p><p>${r.hours} repair hours served this round · ${E.remaining(state,t)}h outstanding</p>${queue?`<p class="queue">${esc(queue)}</p>`:''}${state.analyses.some(a=>a.team===t)?'<p class="queue">Analysis is pending.</p>':''}</article>`;}).join('');
 $('recent').innerHTML=state.log.slice(-7).reverse().map(x=>`<li><time>${x.settlement?'Settlement':'R'+x.round}</time>${esc(x.text)}</li>`).join('');
 $('result').hidden=state.status!=='ended';if(state.status==='ended'){const type=state.result.type,success=type==='success';$('result').className='panel result '+(success?'success':type==='practice'?'':'failure');const heading={success:'Ironhold is defended.',bankrupt:'The factory has stopped.',targetMissed:'The shipment target was missed.',practice:'Practice session complete.'}[type];$('result').innerHTML=`<h2>${heading}</h2><p>${state.shipped} approved Titans. ${gold} gold remaining across all guilds. ${repair} already-paid repair hours remain outstanding.</p>${success?`<p><b>Master Guild${state.result.winners.length>1?'s':''}:</b> ${state.result.winners.map(t=>esc(E.TEAMS[t].name)).join(', ')}.</p>`:`<p>${type==='practice'?'Review output and survival; practice mode awards no target victory.':'No Master Guild is awarded when the factory fails.'}</p>`}${state.analyses.length?`<p>${state.analyses.length} analysis task(s) remain unresolved because bankruptcy ended play.</p>`:''}`;}
 renderLedger();switchTab(tab);
}
function renderLedger(){const table=(headers,rows)=>`<div class="scroll"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;let html='<h2>Guild ledger</h2><p class="muted">Repairs are paid when issued. Hours served are not charged again. Only Quality output is a factory shipment.</p>';
 html+=table(['Guild','Gold','Spent','Transferred units','Outstanding hours'],E.TEAMS.map((t,i)=>`<tr><td>${esc(t.name)}</td><td>${state.teams[i].gold}</td><td>${10-state.teams[i].gold}</td><td>${state.teams[i].units}</td><td>${E.remaining(state,i)}</td></tr>`));
 html+='<h2>Round results</h2>'+table(['Round','Shipped this round','Cumulative shipped','Factory gold at round end'],state.rounds.map(r=>`<tr><td>${r.round}</td><td>${r.shipped}</td><td>${r.cumulative}</td><td>${r.gold.reduce((a,b)=>a+b,0)}</td></tr>`));
 html+='<h2>Repair tickets</h2>'+table(['Issued','Charged team','Reason','Hours','Gold','Due'],state.tickets.map(t=>`<tr><td>${t.settlement?'Settlement':'R'+t.round}</td><td>${role(t.team)}</td><td>${esc(t.reason)}</td><td>${t.hours}</td><td>${t.cost}</td><td>${t.hours?'R'+t.due:'None'}</td></tr>`));
 html+='<h2>Complete event history</h2><p class="muted">Every dice outcome, reroll, decision, transfer and charge. Saving preserves this history through replay.</p><ol class="event-list">'+state.log.map(x=>`<li><time>${x.settlement?'Settlement':'R'+x.round}</time>${esc(x.text)}</li>`).join('')+'</ol>';$('ledger').innerHTML=html;
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$('mode').onchange=()=>{$('target-label').hidden=$('mode').value!=='target';$('target').required=$('mode').value==='target';};
$('setup-form').onsubmit=e=>{e.preventDefault();try{state=E.newGame({name:$('session-name').value.trim(),target:$('mode').value==='target'?Number($('target').value):null});message('');tab='play';update();}catch(err){message(err.message,true);}};
$('read-before').onclick=()=>switchTab('rules');
$('save').onclick=()=>download('Ironhold_R'+state.round+'_save.json',E.serialize(state),'application/json');
$('csv').onclick=()=>download('Ironhold_ledger.csv','\ufeff'+E.csv(state),'text/csv;charset=utf-8');
$('load').onclick=()=>$('load-file').click();
$('load-file').onchange=async()=>{const f=$('load-file').files[0];$('load-file').value='';if(!f)return;if(f.size>2000000){message('Save file is too large (maximum 2 MB).',true);return;}try{const loaded=E.deserialize(await f.text());if(state&&!confirm('Replace the current session with this saved game? Save your current session first if you need it.'))return;state=loaded;tab='play';message('Saved game loaded and validated.');update();}catch(err){message(err.message,true);}};
$('undo').onclick=()=>{if(!confirm('Undo the last entry? Use this only to correct an input error, not to reroll an unfavorable outcome.'))return;try{state=E.undo(state);message('Last entry undone.');update();}catch(err){message(err.message,true);}};
$('new-game').onclick=()=>{if(state&&!confirm('Return to setup? Download a save first to keep this session.'))return;state=null;$('setup').hidden=false;$('game').hidden=true;$('welcome').hidden=false;$('ledger').innerHTML='<h2>Ledger &amp; history</h2><p>Start a session to view the ledger.</p>';message('');switchTab('play');render();try{$('resume').hidden=!localStorage.getItem(KEY);}catch{}};
$('resume').onclick=()=>{try{const text=localStorage.getItem(KEY);state=E.deserialize(text);message('Previous session restored.');tab='play';update();}catch(err){message('Could not restore this save: '+err.message,true);}};
try{$('resume').hidden=!localStorage.getItem(KEY);}catch{storageOK=false;}
render();
})();
