(function(){
'use strict';
const E=window.Ironhold,$=id=>document.getElementById(id),KEY='ironhold-standalone-3.0.0';let state=null,tab='play',storageOK=true,rollReview=false,gmMode=false,viewer=null,showcase=false,guildTab='dice';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const role=t=>E.TEAMS[t].role;
const icons=['<path d="M4 20V8l5 3V8l5 3V5h6v15H4Z"/><path d="M7 15h2m3 0h2m3 0h1"/>','<circle cx="12" cy="12" r="5"/><path d="M12 2v5m0 10v5M2 12h5m10 0h5M5 5l4 4m6 6 4 4M5 19l4-4m6-6 4-4"/>','<path d="m12 3 8 4v10l-8 4-8-4V7l8-4Zm0 8v10M4 7l8 4 8-4"/>','<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="8" y="15" width="8" height="6" rx="1"/><path d="M6 10v3h12v-3m-6 3v2"/>','<path d="M8 4h8v5h4v11H4V9h4V4Z"/><path d="M9 13h6m-6 4h6M12 1v3"/>','<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6l8-4Z"/><path d="m8 12 3 3 5-6"/>'];
const icon=t=>`<svg class="guild-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[t]}</svg>`;
const procurementText=text=>text.replace(/chooses YF/g,'chooses planned supplier corrective action').replace(/chooses YA/g,'chooses supplier risk review').replace(/chooses Red/g,'chooses a quality hold').replace(/selected signal/g,'selected procurement response');
const guildArtNames=['ember','gear','arcane','anvil','titan','gaze'];
const guildPortrait=(t,small=false)=>{const path='assets/guild-'+guildArtNames[t]+'.webp';return `<img class="guild-portrait ${small?'portrait-small':''}" src="${window.IronholdArt?.[path]||path}" alt="${esc(E.TEAMS[t].name)} — ${esc(role(t))} comic portrait" width="480" height="480" loading="lazy">`;};
const guild=t=>`${esc(E.TEAMS[t].name)} <span class="guild-role">(${esc(role(t))})</span>`;
function rollResult(){
 const last=[...state.log].reverse().find(x=>x.type==='die');if(!last)return '';
 const next=state.pending;const labels={production:'Production',event:'Procurement exception',solution:'Corrective action',origin:'Supplier attribution',analysis:'Supplier risk review'};
 let outcome;
 if(last.kind==='production')outcome=last.value<=3?'D10 required for this roll · partial capacity: 1 unit. Identify the procurement exception.':'No D10 required for this roll · full base capacity: 2 units. Actual transfer still depends on inputs and corrective work.';
 else if(last.kind==='event')outcome=next?.kind==='event'?'Roll D10 again · this result is odd or does not apply to this team. No charge.':`D10 complete · ${E.EVENTS[last.value]}. Follow the response below.`;
 else outcome=next?.kind===last.kind&&next?.team===last.team?'This result does not apply; roll again.':'Roll recorded. Follow the next action below.';
 return `<section id="roll-result" class="roll-result ${last.kind==='production'&&last.value>3?'clear':'alert'}" aria-live="polite"><div class="rolled-value"><small>D${last.sides}</small><strong>${last.value}</strong></div><div><p class="eyebrow">${labels[last.kind]} result · Round ${last.round}</p><b>${guild(last.team)}</b><p>${esc(outcome)}</p><small>${state.log.filter(x=>x.type==='die').length} total rolls recorded · Last completed roll</small></div></section>`;
}
function message(text,error=false){$('message').textContent=text;$('message').hidden=!text;$('message').classList.toggle('error',error);if($('guild-message')){$('guild-message').textContent=text;$('guild-message').className=error?'message error':'message';}}
function switchTab(value){tab=value;document.body.dataset.scene=value;for(const name of ['play','ledger','rules'])$(name+'-view').hidden=name!==value;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===value)));}
function persist(){if(!state)return;try{localStorage.setItem(KEY,E.serialize(state));storageOK=true;}catch{storageOK=false;}}
function update(){render();persist();if(state)$('autosave').textContent=storageOK?'Autosaved in this browser. Download a game save before leaving or changing devices.':'Browser storage is unavailable. Use Save game to keep your progress.';}
function act(action){try{if(viewer===null||showcase)throw new Error('Choose a role before acting.');if(Number.isInteger(viewer)){const p=state.pending;const allowed=action.type==='transfer'?action.from===viewer:['die','signal'].includes(action.type)&&p?.team===viewer&&p.kind!=='vendor';if(!allowed)throw new Error('This action belongs to the Game Master or another guild.');}state=E.dispatch(state,action);rollReview=action.type==='die';message('');update();}catch(err){message(err.message,true);}}
function dice(sides){const limit=Math.floor(4294967296/sides)*sides;let value;do{const a=new Uint32Array(1);crypto.getRandomValues(a);value=a[0];}while(value>=limit);return value%sides+1;}
function download(name,text,mime){const url=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function stageName(){return state.settlement?'Final settlement':`Round ${state.round} · Stage ${state.stage+1} of 4`;}
function badge(signal){const cls=signal==='Green'?'green':signal==='Red'||signal==='Maintenance'?'red':['YF','YA','Vendor'].includes(signal)?'yellow':'';return `<span class="badge ${cls}">${esc(({Green:'Supply clear',Red:'Quality hold',YF:'Planned action',YA:'Risk review',Vendor:'Supplier review',Maintenance:'Corrective work',Idle:'Awaiting inputs'}[signal])||signal||'Awaiting turn')}</span>`;}
function pendingHelp(p){const r=state.rows.find(r=>r.round===state.round&&r.team===p.team);if(p.kind==='production')return ['Production roll','1–3: one-unit base capacity. 4–6: two-unit base capacity. Inputs and repairs can reduce the actual transfer.'];if(p.kind==='event')return ['Procurement exception roll','Roll D10. Odd or inapplicable outcomes require another roll. A physical 0 means 10.'];if(p.kind==='solution'){const valid=[1,2,3,4].filter(n=>E.validSolution(r.event,n));return ['Find an applicable solution',`${E.EVENTS[r.event]}. Valid faces: ${valid.join(', ')}. Other results reroll without changing the procurement response.`];}if(p.kind==='origin')return ['Identify the rework origin',p.team===3?'1–3: Shop 1. 4–6: Shop 2. The origin pays 2 gold and repairs next round.':'1–3: Subassembly. 4–6: Shop 3. The origin pays 2 gold and repairs next round.'];return ['Resolve deferred analysis','1–2: close at no cost. 3–4: 4h / 1 gold. 5–6: 8h / 2 gold. '+(state.settlement?'No more production occurs.':'Repair hours are served before this round’s production.')];}
function actionPanel(){const p=state.pending;$('phase-label').textContent=stageName();$('roll-summary').innerHTML=rollResult();if(rollReview){$('action').innerHTML='<h2 id="action-title">Review the roll above</h2><p>Discuss the result with the team, then continue to the next decision.</p><button id="continue-roll" class="primary">'+(p?.kind==='event'?'Continue to separate D10 roll':'Continue to next action')+'</button>';$('continue-roll').onclick=()=>{rollReview=false;render();};return;}if(!p){$('action').innerHTML='<h2 id="action-title">The session is complete</h2><p>Review the factory result, compare guild decisions and export your ledger.</p><button id="review-ledger" class="primary">Review the ledger</button>';$('review-ledger').onclick=()=>switchTab('ledger');return;}
 let html=p.team!==null?`<p class="guild-name">${icon(p.team)} ${guild(p.team)}</p>`:'';
 if(p.sides){const [heading,help]=pendingHelp(p);const last=[...state.log].reverse().find(x=>x.type==='die');html+=`<h2 id="action-title">${heading}</h2><div class="die-box"><div class="die-face" aria-label="${p.sides}-sided die">d${p.sides}</div><p>${esc(help)}</p></div><button id="${p.kind==='event'?'roll-d10':'roll'}" class="primary dice-button">${p.kind==='event'?'Roll D10 · procurement exception':'Roll D'+p.sides+' · '+({production:'production',solution:'corrective action',origin:'supplier attribution',analysis:'risk review'}[p.kind])}</button><div class="manual-row"><label>Physical die result<input id="manual-die" type="number" min="1" max="${p.sides}" step="1" inputmode="numeric" aria-label="Physical die result"></label><button id="record-die">Record roll</button></div><p class="muted small">${last?`Last roll: ${esc(last.kind)} d${last.sides} = <b>${last.value}</b>.`:'Every die outcome is recorded in the history.'}</p>`;
 }
 else if(p.kind==='signal'){const r=state.rows.find(r=>r.round===state.round&&r.team===p.team);html+=`<h2 id="action-title">How will you respond?</h2><p>Partial capacity: 1. Cause: <b>${esc(E.EVENTS[r.event])}</b>. Discuss the downstream effect before choosing.</p><button class="decision" data-signal="YF"><b>Planned supplier corrective action</b><small>Choose a solution and pay now. Serve repair hours next round.</small></button><button class="decision" data-signal="YA"><b>Supplier risk review</b><small>Resolve a 0h, 4h or 8h outcome next round.</small></button><button class="decision red" data-signal="Red"><b>Quality hold · immediate corrective action</b><small>Choose a solution and serve repair hours before releasing output.</small></button>`;}
 else if(p.kind==='vendor'){html+=`<h2 id="action-title">Keep or change the vendor?</h2><p>Occurrence <b>${state.vendor.count} of 3</b>. A majority for change charges each shop 2 gold and schedules 8 repair hours next round.</p><div class="votes">${[0,1,2].map(t=>`<label>${role(t)} vote<select id="vote-${t}"><option value="">Choose a vote</option><option value="keep">Keep vendor</option><option value="change">Change vendor</option></select></label>`).join('')}</div><button id="submit-vote" class="primary">Record the three votes</button>`;}
 else if(p.kind==='release'){html+=`<h2 id="action-title">Release stage ${state.stage+1} output</h2><p>All decisions for ${E.STAGES[state.stage].map(role).join(' and ')} are complete. Predict the actual output before releasing it.</p><div class="scroll"><table><thead><tr><th>Team</th><th>Base</th><th>Repair hours</th><th>Rework hold</th></tr></thead><tbody>${E.STAGES[state.stage].map(t=>{const r=state.rows.find(r=>r.round===state.round&&r.team===t);return `<tr><td>${role(t)}</td><td>${r.base}</td><td>${r.hours}</td><td>${r.hold?'Yes':'No'}</td></tr>`;}).join('')}</tbody></table></div><button id="release" class="primary">Transfer good units</button>`;}
 else if(p.kind==='roundEnd'){const cycleBreak=[5,10,15].includes(state.round);html+=`<h2 id="action-title">${state.round===15?'Production complete':cycleBreak?'Pause for the cycle debrief':`Round ${state.round} complete`}</h2><p>${state.rounds.at(-1).shipped} Titans shipped this round. ${state.shipped} approved in total.</p>${cycleBreak?'<div class="debrief"><h3>Discuss before continuing</h3><ul><li>Which shortage or repair constrained the factory?</li><li>Did saving local gold help the common mission?</li><li>What will your team do differently?</li></ul></div>':''}<p class="muted">${state.round===15?'Final settlement resolves any deferred analysis before scoring. Already-paid outstanding repairs are not charged again.':'Cash, inventories, vendor protection and queued repairs carry forward.'}</p><button id="next" class="primary">${state.round===15?'Settle outstanding analysis':'Begin round '+(state.round+1)}</button>`;}
 $('action').innerHTML=html;
 const rollButton=$('roll-d10')||$('roll');if(rollButton)rollButton.onclick=()=>{try{act({type:'die',value:dice(p.sides)});}catch(err){message('Virtual dice are unavailable. Enter a physical die result.',true);}};
 if($('record-die')){$('record-die').onclick=()=>act({type:'die',value:Number($('manual-die').value)});$('manual-die').onkeydown=e=>{if(e.key==='Enter')$('record-die').click();};}
 document.querySelectorAll('[data-signal]').forEach(b=>b.onclick=()=>act({type:'signal',value:b.dataset.signal}));
 if($('submit-vote'))$('submit-vote').onclick=()=>{const v=[0,1,2].map(t=>$('vote-'+t).value);if(v.some(x=>!x)){message('Record each of the three shop votes.',true);return;}act({type:'vendor',votes:v.map(x=>x==='change')});};
 if($('release'))$('release').onclick=()=>act({type:'release'});
 if($('next'))$('next').onclick=()=>act({type:'next'});
}
function render(){roleShell();const playing=!!state;if(Number.isInteger(viewer)){renderGuild();return;}$('setup').hidden=playing;$('welcome').hidden=playing;$('game').hidden=!playing;for(const id of ['save','csv'])$(id).disabled=!playing;$('undo').disabled=!playing||!state.actions.length;if(!playing)return;
 const gold=state.teams.reduce((n,t)=>n+t.gold,0),target=state.config.target,repair=state.teams.reduce((n,_,i)=>n+E.remaining(state,i),0);
 $('metrics').innerHTML=`<div class="metric"><span>${esc(state.config.name||'Classroom session')}</span><strong>${state.settlement?'Settlement':'Round '+state.round+' / 15'}</strong><small>Cycle ${Math.ceil(state.round/5)} · ${['Early Dawn','Fires of Noon','Twilight of Battle'][Math.ceil(state.round/5)-1]}</small></div><div class="metric"><span>Approved Titans</span><strong>${state.shipped}${target!==null?' / '+target:''}</strong><small>${target===null?'Practice · no target victory':'All guilds must also survive'}</small><div class="progress"><span style="width:${Math.min(100,100*state.shipped/(target||30))}%"></span></div></div><div class="metric"><span>Total gold · initial baseline below</span><strong>${gold} / ${6*state.config.startingGold}</strong><small>Every individual guild must stay above 0</small></div><div class="metric"><span>Outstanding work</span><strong>${repair} hours</strong><small>${state.analyses.length} analysis task${state.analyses.length===1?'':'s'} pending</small></div>`;
 treasuryPanel();actionPanel();
 const node=(label,count,unit)=>`<div class="node"><b>${label}</b><strong>${count}</strong><small>${unit}</small></div>`;
 $('network').innerHTML=[`<div class="flow-nodes">${node('Shop 1',state.buffers[0],'C1 waiting')}${node('Shop 2',state.buffers[1],'C2 waiting')}</div>`,`<div class="flow-nodes">${node('Shop 3',state.buffers[2],'C3 waiting')}${node('Subassembly',state.buffers[3],'waiting')}</div>`,`<div class="flow-nodes">${node('Final assembly',state.buffers[4],'awaiting inspection')}</div>`,`<div class="flow-nodes">${node('Quality approved',state.shipped,'Titans shipped')}</div>`].map((content,i)=>`<div class="flow-stage ${state.status==='playing'&&!state.settlement&&state.stage===i?'current':''}"><span>Stage ${i+1}</span>${content}</div>`).join('');
 $('vendor-info').innerHTML=`<p><b>Vendor:</b> ${state.vendor.count} / 3 occurrences · ${state.vendor.changes} change${state.vendor.changes===1?'':'s'}.</p><p>${state.round<=state.vendor.protectedThrough?`Protected through round <b>${state.vendor.protectedThrough}</b>; event 8 is rerolled.`:'No active protection. A third occurrence forces a change.'}</p>`;
 $('team-cards').innerHTML=E.TEAMS.map((team,t)=>{const own=state.teams[t],r=state.rows.find(r=>r.round===state.round&&r.team===t),queue=own.queue.map(q=>`${q.hours}h due R${q.due}`).join('; ');return `<article class="team-card ${state.pending?.team===t?'active':''} ${own.gold<=0?'bankrupt':''}">${guildPortrait(t)}<div class="guild-heading">${icon(t)}<h3>${guild(t)}</h3></div><div class="team-line"><span class="money">${own.gold} <small>gold</small></span>${badge(r.signal)}</div><p><b>${r.released?r.output:'—'}</b> transferred this round · <b>${own.units}</b> total units</p><p>${r.hours} repair hours served this round · ${E.remaining(state,t)}h outstanding</p>${queue?`<p class="queue">${esc(queue)}</p>`:''}${state.analyses.some(a=>a.team===t)?'<p class="queue">Analysis is pending.</p>':''}</article>`;}).join('');
 $('recent').innerHTML=state.log.slice(-7).reverse().map(x=>`<li><time>${x.settlement?'Settlement':'R'+x.round}</time>${esc(procurementText(x.text))}</li>`).join('');
 $('result').hidden=state.status!=='ended';if(state.status==='ended'){const type=state.result.type,success=type==='success';$('result').className='panel result '+(success?'success':type==='practice'?'':'failure');const heading={success:'Ironhold is defended.',bankrupt:'The factory has stopped.',targetMissed:'The shipment target was missed.',practice:'Practice session complete.'}[type];$('result').innerHTML=`<h2>${heading}</h2><p>${state.shipped} approved Titans. ${gold} gold remaining across all guilds. ${repair} already-paid repair hours remain outstanding.</p>${success?`<p><b>Master Guild${state.result.winners.length>1?'s':''}:</b> ${state.result.winners.map(t=>esc(E.TEAMS[t].name)).join(', ')}.</p>`:`<p>${type==='practice'?'Review output and survival; practice mode awards no target victory.':'No Master Guild is awarded when the factory fails.'}</p>`}${state.analyses.length?`<p>${state.analyses.length} analysis task(s) remain unresolved because bankruptcy ended play.</p>`:''}`;}
 renderLedger();switchTab(tab);roleShell();
}
function treasuryPanel(){
 $('starting-rule').textContent=`Starting rule: ${state.config.startingGold} gold per guild`;
 $('transfer-submit').disabled=state.status!=='playing';$('gm-submit').disabled=state.status!=='playing';
 $('gm-round').textContent=state.status==='ended'?'This game has ended. Use Undo for an entry error or start a new session.':state.settlement?'Final settlement · gold adjustments and notes only.':`Round ${state.round} · exceptions are recorded against this round.`;
 transferPreview();gmHelp();
}
function transferPreview(){if(!state)return;const f=Number($('transfer-from').value),t=Number($('transfer-to').value),n=Number($('transfer-amount').value);$('transfer-preview').textContent=`${role(f)}: ${state.teams[f].gold} gold → ${state.teams[f].gold-n}. ${role(t)}: ${state.teams[t].gold} gold → ${state.teams[t].gold+n}. Sender must keep at least 1 gold.`;}
function gmHelp(){const k=$('gm-kind').value;$('gm-gold-label').hidden=k!=='gold';$('gm-hours-label').hidden=k!=='downtime';$('gm-help').textContent=k==='gold'?'Positive adds gold; negative deducts gold. Applied per selected guild. A balance of zero or less ends the game.':k==='downtime'?'No gold charge. Adds queued downtime from next round; existing work is retained. Available in rounds 1–14 only.':'Record an instructor instruction for this round. A note does not automatically change dice, production, stock or costs.';}
function renderLedger(){const table=(headers,rows)=>`<div class="scroll"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;let html='<h2>Guild ledger</h2><p class="muted">Repairs are paid when issued. Hours served are not charged again. Only Quality output is a factory shipment.</p>';
 html+=table(['Guild','Gold','Repair costs','Cash movements (net)','Transferred units','Outstanding hours'],E.TEAMS.map((t,i)=>`<tr><td><div class="ledger-guild">${guildPortrait(i,true)}<span>${guild(i)}</span></div></td><td>${state.teams[i].gold}</td><td>${state.tickets.filter(x=>x.team===i).reduce((n,x)=>n+x.cost,0)}</td><td>${state.cashMoves.filter(x=>x.team===i).reduce((n,x)=>n+x.delta,0)}</td><td>${state.teams[i].units}</td><td>${E.remaining(state,i)}</td></tr>`));
 html+='<h2>Gold transfers &amp; adjustments</h2>'+table(['Round','Guild','Change','Type','Counterparty','Reason'],state.cashMoves.map(m=>`<tr><td>${m.settlement?'Settlement':m.round}</td><td>${role(m.team)}</td><td>${m.delta>0?'+':''}${m.delta}</td><td>${m.kind==='transfer'?'Guild transfer':'Game Master'}</td><td>${m.other===null?'—':role(m.other)}</td><td>${esc(m.reason)}</td></tr>`));
 html+='<h2>Round results</h2>'+table(['Round','Shipped this round','Cumulative shipped','Factory gold at round end'],state.rounds.map(r=>`<tr><td>${r.round}</td><td>${r.shipped}</td><td>${r.cumulative}</td><td>${r.gold.reduce((a,b)=>a+b,0)}</td></tr>`));
 html+='<h2>Repair tickets</h2>'+table(['Issued','Charged team','Reason','Hours','Gold','Due'],state.tickets.map(t=>`<tr><td>${t.settlement?'Settlement':'R'+t.round}</td><td>${role(t.team)}</td><td>${esc(t.reason)}</td><td>${t.hours}</td><td>${t.cost}</td><td>${t.hours?'R'+t.due:'None'}</td></tr>`));
 html+='<h2>Complete event history</h2><p class="muted">Every dice outcome, reroll, decision, transfer and charge. Saving preserves this history through replay.</p><ol class="event-list">'+state.log.map(x=>`<li><time>${x.settlement?'Settlement':'R'+x.round}</time>${esc(procurementText(x.text))}</li>`).join('')+'</ol>';$('ledger').innerHTML=html;
}
function roleShell(){
 $('role-entry').hidden=viewer!==null;$('role-bar').hidden=viewer===null;$('master-workspace').hidden=viewer!=='gm'||showcase;$('guild-workspace').hidden=!Number.isInteger(viewer)||showcase;$('showcase-workspace').hidden=!showcase;
 $('role-label').textContent=viewer==='gm'?(showcase?'Game Master · classroom reveal':'Game Master · full factory view'):Number.isInteger(viewer)?E.TEAMS[viewer].name+' ('+role(viewer)+')':'';
 $('open-reveal').hidden=viewer!=='gm'||!state||showcase;$('close-reveal').hidden=!showcase;
}
function chooseRole(v){
 if(v!=='gm'&&!state){try{const saved=localStorage.getItem(KEY);if(saved)state=E.deserialize(saved);}catch{}if(!state){$('role-entry-message').textContent='The Game Master must start a session in this browser first.';return;}}
 viewer=v;guildTab='dice';if(Number.isInteger(v))document.body.dataset.scene='play';showcase=false;rollReview=false;gmMode=false;$('gm-panel').hidden=true;$('gm-toggle').textContent='Enter Game Master mode';$('gm-toggle').setAttribute('aria-expanded','false');message('');render();
}
function ownLogs(t){return state.log.filter(x=>x.team===t||(x.type==='exception'&&x.team===null));}
function renderGuild(){
 const t=viewer,team=E.TEAMS[t],own=state.teams[t],p=state.pending,r=state.rows.find(x=>x.round===state.round&&x.team===t),can=p?.team===t&&p.kind!=='vendor'&&state.status==='playing';
 const last=[...state.log].reverse().find(x=>x.type==='die'&&x.team===t);let action='';
 if(state.status==='ended')action='<p>The session has ended. The Game Master can showcase the full factory results.</p>';
 else if(p?.kind==='vendor')action='<p>The Game Master is collecting supplier votes. '+(t<3?'Tell the instructor whether your shop votes to keep or change the supplier.':'Wait for the shop vote to finish.')+'</p>';
 else if(!can)action='<p>Waiting for the Game Master or another guild. Your information remains below.</p>';
 else if(rollReview)action='<button id="guild-continue" class="primary">Review complete · continue</button>';
 else if(p.sides){const [heading,help]=pendingHelp(p);action=`<h3>${heading}</h3><p>${esc(help)}</p><button id="guild-roll" class="primary">Roll D${p.sides}${p.kind==='event'?' · procurement exception':''}</button><div class="manual-row"><label>Physical die result<input id="guild-die" type="number" min="1" max="${p.sides}" step="1"></label><button id="guild-record">Record roll</button></div>`;}
 else if(p.kind==='signal')action='<p>Choose your procurement response.</p>'+[['YF','Planned supplier corrective action'],['YA','Supplier risk review'],['Red','Quality hold · immediate action']].map(([v,label])=>`<button class="decision" data-guild-signal="${v}">${label}</button>`).join('');
 const inputs=team.inputs.length?team.inputs.map(i=>`${E.BUFFERS[i]}: ${state.buffers[i]}`).join(' · '):'Raw material input: available subject to supplier events';
 const output=t===5?'Your approved shipments: '+own.units:'Your output buffer: '+state.buffers[team.out];
 const rolls=last?`<div class="roll-result"><div class="rolled-value"><small>D${last.sides}</small><strong>${last.value}</strong></div><div><b>Your latest roll · round ${last.round}</b><p>${last.kind==='production'?(last.value<=3?'D10 required for this production roll.':'No D10 required for this production roll.'):esc(last.kind)+' roll recorded.'}</p></div></div>`:'';
 const moves=state.cashMoves.filter(x=>x.team===t);
 $('guild-workspace').innerHTML=`<div class="panel guild-private-header">${guildPortrait(t,true)}<div><h2>${guild(t)}</h2><p>Round ${state.round} / 15 · ${state.settlement?'Final settlement':state.status==='ended'?'Session complete':'Guild dashboard'}</p></div></div><p class="role-notice">This shared-browser view filters the display. It is not secure, separate-device multiplayer.</p><p id="guild-message" role="status"></p><div class="metrics"><div class="metric"><span>Your gold</span><strong>${own.gold}</strong></div><div class="metric"><span>Your total units</span><strong>${own.units}</strong></div><div class="metric"><span>Your queued downtime</span><strong>${E.remaining(state,t)}h</strong></div><div class="metric"><span>Your status</span>${badge(r.signal)}</div></div><div class="guild-tabs" role="tablist" aria-label="Guild pages"><button id="guild-tab-dice" role="tab" aria-controls="guild-panel-dice">⚄ Roll dice</button><button id="guild-tab-overview" role="tab" aria-controls="guild-panel-overview">Guild stock &amp; history</button></div><section id="guild-panel-dice" class="panel" role="tabpanel" aria-labelledby="guild-tab-dice"><h2>Your dice &amp; decisions</h2><p>Only the die required by the current rule is available on your turn. Review each result before continuing.</p>${rolls}${action}</section><div id="guild-panel-overview" role="tabpanel" aria-labelledby="guild-tab-overview"><section class="panel"><h2>Your stock &amp; work</h2><p>${esc(inputs)}</p><p>${esc(output)}</p><p>${r.hours}h downtime served this round. ${state.analyses.filter(x=>x.team===t).length} risk reviews pending.</p><p>${own.queue.map(q=>q.hours+'h due round '+q.due).join(' · ')||'No queued downtime.'}</p></section><section class="panel"><h2>Your gold transfers</h2><form id="guild-transfer-form"><label>Receiving guild<select id="guild-recipient">${E.TEAMS.map((x,i)=>i===t?'':`<option value="${i}">${esc(x.name)} (${x.role})</option>`).join('')}</select></label><label>Gold to send<input id="guild-amount" type="number" min="1" max="${Math.max(1,own.gold-1)}" step="1" value="1" required></label><label>Agreement / reason<input id="guild-reason" minlength="3" maxlength="240" required></label><p>You must retain at least 1 gold.</p><button class="primary" ${state.status==='ended'?'disabled':''}>Send gold</button></form><ol>${moves.map(m=>`<li>Round ${m.round}: ${m.delta>0?'+':''}${m.delta} gold ${m.other===null?'(Game Master)':(m.delta>0?'from ':'to ')+esc(role(m.other))} · ${esc(m.reason)}</li>`).join('')||'<li>No transfers or adjustments.</li>'}</ol></section><section class="panel"><h2>Your event history</h2><ol class="event-list">${ownLogs(t).map(x=>`<li>Round ${x.round} · ${esc(procurementText(x.text))}</li>`).join('')||'<li>No events yet.</li>'}</ol></section></div>`;
 $('guild-workspace').insertAdjacentHTML('beforeend','<details class="panel"><summary>Read the common game rules</summary>'+document.querySelector('#rules-view .rules').innerHTML+'</details>');
 function selectGuildTab(name,focus=false){guildTab=name;['dice','overview'].forEach(k=>{const b=$('guild-tab-'+k),active=k===name;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$('guild-panel-'+k).hidden=!active;});if(focus)$('guild-tab-'+name).focus();}
 ['dice','overview'].forEach(name=>{const b=$('guild-tab-'+name);b.onclick=()=>selectGuildTab(name);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();selectGuildTab(e.key==='Home'?'dice':e.key==='End'?'overview':name==='dice'?'overview':'dice',true);}};});selectGuildTab(guildTab);
 if($('guild-continue'))$('guild-continue').onclick=()=>{rollReview=false;renderGuild();};
 if($('guild-roll'))$('guild-roll').onclick=()=>act({type:'die',value:dice(p.sides)});
 if($('guild-record'))$('guild-record').onclick=()=>act({type:'die',value:Number($('guild-die').value)});
 document.querySelectorAll('[data-guild-signal]').forEach(b=>b.onclick=()=>act({type:'signal',value:b.dataset.guildSignal}));
 $('guild-transfer-form').onsubmit=e=>{e.preventDefault();act({type:'transfer',from:t,to:Number($('guild-recipient').value),amount:Number($('guild-amount').value),reason:$('guild-reason').value});};
}
function revealRound(){
 if(viewer!=='gm'||!state)return;const round=Number($('reveal-round').value);let snap=E.newGame(state.config);
 for(const a of state.actions){const next=E.dispatch(snap,a);if(next.round>round)break;snap=next;}
 const complete=snap.rounds.some(x=>x.round===round);$('reveal-content').innerHTML=`<h3>Round ${round} · ${complete?'recorded end of round':'recorded so far'}</h3><p>${snap.shipped} Titans shipped in total. ${snap.teams.reduce((n,t)=>n+t.gold,0)} gold across all guilds.</p><div class="scroll"><table><thead><tr><th>Guild</th><th>Gold</th><th>Total units</th><th>Queued downtime</th></tr></thead><tbody>${E.TEAMS.map((t,i)=>`<tr><td><div class="ledger-guild">${guildPortrait(i,true)}${guild(i)}</div></td><td>${snap.teams[i].gold}</td><td>${snap.teams[i].units}</td><td>${E.remaining(snap,i)}h</td></tr>`).join('')}</tbody></table></div><h3>Decisions and events in this round</h3><ol class="event-list">${snap.log.filter(x=>x.round===round).map(x=>`<li>${x.settlement?'Final settlement · ':''}${esc(procurementText(x.text))}</li>`).join('')}</ol>`;
}
$('role-options').innerHTML='<button class="role-choice" data-role="gm"><img src="'+(window.IronholdArt?.['assets/game-master.webp']||'assets/game-master.webp')+'" alt="Game Master wizard"><b>Game Master</b><span>Manage all guilds and reveal results</span></button>'+E.TEAMS.map((t,i)=>`<button class="role-choice" data-role="${i}">${guildPortrait(i,true)}<b>${esc(t.name)}</b><span>${t.role} · own dashboard</span></button>`).join('');
document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>chooseRole(b.dataset.role==='gm'?'gm':Number(b.dataset.role)));
$('switch-role').onclick=()=>{viewer=null;showcase=false;roleShell();$('role-entry-message').textContent='Choose the next role. The game is retained in this browser.';};
$('open-reveal').onclick=()=>{if(viewer!=='gm'||!state)return;showcase=true;$('reveal-round').innerHTML=Array.from({length:state.round},(_,i)=>`<option value="${i+1}">Round ${i+1}</option>`).join('');$('reveal-round').value=String(state.round);roleShell();revealRound();};
$('close-reveal').onclick=()=>{showcase=false;render();};$('reveal-round').onchange=revealRound;
const teamOptions=E.TEAMS.map((t,i)=>`<option value="${i}">${esc(t.name)} (${esc(t.role)})</option>`).join('');
$('transfer-from').innerHTML=teamOptions;$('transfer-to').innerHTML=teamOptions;$('transfer-to').value='1';$('gm-team').insertAdjacentHTML('beforeend',teamOptions);
for(const id of ['transfer-from','transfer-to','transfer-amount'])$(id).oninput=transferPreview;
$('transfer-form').onsubmit=e=>{e.preventDefault();act({type:'transfer',from:Number($('transfer-from').value),to:Number($('transfer-to').value),amount:Number($('transfer-amount').value),reason:$('transfer-reason').value});};
$('gm-toggle').onclick=()=>{if(viewer!=='gm'||showcase)return;gmMode=!gmMode;$('gm-panel').hidden=!gmMode;$('gm-toggle').textContent=gmMode?'Leave Game Master mode':'Enter Game Master mode';$('gm-toggle').setAttribute('aria-expanded',String(gmMode));};
$('gm-kind').onchange=gmHelp;
$('gm-form').onsubmit=e=>{e.preventDefault();if(!gmMode)return;const kind=$('gm-kind').value,team=$('gm-team').value==='all'?null:Number($('gm-team').value),amount=kind==='gold'?Number($('gm-gold').value):kind==='downtime'?Number($('gm-hours').value):0;if(kind==='gold'&&amount<0&&(team===null?state.teams:[state.teams[team]]).some(t=>t.gold+amount<=0)&&!confirm('This penalty will bankrupt a guild and end the game. Apply it?'))return;act({type:'exception',kind,team,amount,reason:$('gm-reason').value,instructor:$('gm-name').value});};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$('mode').onchange=()=>{$('target-label').hidden=$('mode').value!=='target';$('target').required=$('mode').value==='target';};
$('setup-form').onsubmit=e=>{e.preventDefault();if(viewer!=='gm'||showcase)return;try{state=E.newGame({name:$('session-name').value.trim(),target:$('mode').value==='target'?Number($('target').value):null,startingGold:Number($('starting-gold').value)});message('');tab='play';update();}catch(err){message(err.message,true);}};
$('read-before').onclick=()=>switchTab('rules');
$('save').onclick=()=>viewer==='gm'&&!showcase&&download('Ironhold_R'+state.round+'_save.json',E.serialize(state),'application/json');
$('csv').onclick=()=>viewer==='gm'&&!showcase&&download('Ironhold_ledger.csv','\ufeff'+E.csv(state),'text/csv;charset=utf-8');
$('load').onclick=()=>{if(viewer==='gm'&&!showcase)$('load-file').click();};
$('load-file').onchange=async()=>{const f=$('load-file').files[0];$('load-file').value='';if(!f)return;if(f.size>2000000){message('Save file is too large (maximum 2 MB).',true);return;}try{const loaded=E.deserialize(await f.text());if(state&&!confirm('Replace the current session with this saved game? Save your current session first if you need it.'))return;state=loaded;rollReview=false;tab='play';message('Saved game loaded and validated.');update();}catch(err){message(err.message,true);}};
$('undo').onclick=()=>{if(viewer!=='gm'||showcase)return;if(!confirm('Undo the last entry? Use this only to correct an input error, not to reroll an unfavorable outcome.'))return;try{state=E.undo(state);rollReview=false;message('Last entry undone.');update();}catch(err){message(err.message,true);}};
$('new-game').onclick=()=>{if(viewer!=='gm'||showcase)return;if(state&&!confirm('Return to setup? Download a save first to keep this session.'))return;state=null;rollReview=false;$('setup').hidden=false;$('game').hidden=true;$('welcome').hidden=false;$('ledger').innerHTML='<h2>Ledger &amp; history</h2><p>Start a session to view the ledger.</p>';message('');switchTab('play');render();try{$('resume').hidden=!localStorage.getItem(KEY);}catch{}};
$('resume').onclick=()=>{if(viewer!=='gm'||showcase)return;try{const text=localStorage.getItem(KEY);state=E.deserialize(text);rollReview=false;message('Previous session restored.');tab='play';update();}catch(err){message('Could not restore this save: '+err.message,true);}};
try{$('resume').hidden=!localStorage.getItem(KEY);}catch{storageOK=false;}
$('guild-directory').innerHTML=E.TEAMS.map((t,i)=>`<div class="guild-directory-item">${guildPortrait(i,true)}${icon(i)}<span>${guild(i)}</span></div>`).join('');
render();
})();
